Feature/ai responsive neopixels
makerforgetech/modular-biped pull request #87
Opened 2024-09-19 18:35 UTC by SentryCoderDev

2024-10-04 18:09 UTC, danic85 requested changes
Nice work! I can see a big improvement in your code since the last PR. 
Added a few comments that would need addressing to allow it to be merged.

2024-10-04 18:09 UTC, danic85 commented on modules/emotion_analysis.py
> +        pub.subscribe(self.analyze_text, 'speech_recognized')
The correct topic is `speech`: https://github.com/makerforgetech/modular-biped/blob/main/modules/speechinput.py#L57C38-L57C44

2024-10-04 18:09 UTC, danic85 commented on main.py
> +    emotion_analysis = EmotionAnalysis()
We'd need to remove this if we want to merge as it will conflict with the current behaviour of the neopixels. Or disable it in a config file.

2024-10-04 18:09 UTC, danic85 commented on modules/emotions.json
> +{
I have never seen so many colours in my life :laughing: 

This should be in a config file as this deviates from the current design pattern.

2024-10-04 21:50 UTC, SentryCoderDev commented
I think the conflicts have been resolved.

2024-10-05 12:24 UTC, danic85 requested changes

2024-10-05 12:24 UTC, danic85 commented on config/neopixel.yml
> +  enable: true
Nice! Can you chance this to false so it is not enabled by default?

2024-10-05 12:24 UTC, danic85 commented on modules/emotion_analysis_module.py
> +class EmotionAnalysisModule:
You can rename this back to EmotionAnalysis if you prefer, up to you!

2024-10-05 13:30 UTC, danic85 approved these changes

2024-10-18 16:07 UTC, merged